### ISSUE TITLE
SOCRATES crash when inserting stellar spectrum

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/AEOLUS#37]
AEOLUS is provided with a spectral file and a stellar spectrum txt file, and then combines these together at runtime using `prep_spec` from SOCRATES. However, it seems that for files with >100k points the program crashes because of an array index out of bounds error.

```
Fortran runtime error: Index '100001' of dimension 1 of array 'spectrum' above upper bound of 100000
```

This error comes from `inner_bracket.f` when the spectrum is converted to being stored by band rather than by wavelength. The reason for the error is that the array `spectrum` has a fixed maximum length of 100 000, as set by the integer `npd_solar_points` in `dimensions_pp_ucf.f90`.   

For some reason this error only occurs when running on MacOS, possibly because of different compiler options. However, I would expect that it's accessing memory out of bounds on Linux too,  but just isn't being flagged as an error.  

I've found that the error can be mitigated by simply changing the value of `npd_solar_points` to 2 000 000 and recompiling SOCRATES. I suggest two options for going forward:

1. Package a modified version of SOCRATES that has the fix outlined above.
2. Re-bin the stellar spectrum before providing it to SOCRATES such that it has a length of less than 100 000, which would probably result in minimal loss in accuracy.

Personally, I think that Option 2 is preferable as long as we can re-bin the spectrum while conserving energy.

**Comment by nichollsh** [comment]
It's worth noting that we still need high resolution stellar spectra for running VULCAN, which is why I downloaded them in the first place. It's important to resolve peaks in the UV regime for getting the photochemistry right.

**Comment by Nicholaswogan** [comment]
That Fortran runtime error comes from the compiler flag “-fcheck=bounds” if you are using the gfortran compiler. The Linux build must not have that flag. This flag is generally used when doing a “Debug” build, because it actually makes the program quite a bit slower.

The best fix is to just get rid of the fixed compile-time size of the array. Instead use allocatable variables in Socrates to make an array that is just big enough to hold the spectrum at runtime. I don’t have access to the Socrates source code, so I don’t know how easy this fix would be. It’s possible it could be a very simple fix.

However, I think also down binning the spectrum makes sense. 100,000 points is excessive, even for photochemical modeling.

**Comment by nichollsh** [comment]
Thanks for your input, @Nicholaswogan!

You are right about the compiler flags, as the Mac configuration is set-up to include `-fcheck=all` while the Linux one is not.

I think it's probably best to avoid modifying SOCRATES; doing so may create problems with future version changes as we have little control over the development of the code. 

VULCAN re-bins stellar spectra down to ~3000 points by default, with 0.5 nm resolution in the UV. We could adopt a similar approach for AEOLUS when it provides spectra to `prep_spec`.

@timlichtenberg: what do you think?
